<?php

/**
 * @file
 * Install, update and uninstall functions for the r4032login module.
 */

/**
 * Implements hook_enable().
 */
function r4032login_enable() {
  config_set('system.core', 'site_403', 'r4032login');
}

/**
 * Implements hook_disable().
 */
function r4032login_disable() {
  config_set('system.core', 'site_403', '');
}

/**
 * Implements hook_update_last_removed().
 */
function r4032login_update_last_removed() {
  return 7000;
}
